---
title: "final_project"
author: "p8105 group 13"
date: "November 29, 2017"
output: html_document
---
#Motivation: 
Many of us will find a job in recent years. In New York City, what type of job can be payed for higher salary? If that's the ideal job for me , what skills should I have before applying for it?  Also where should I rent an apartment if I want to live close to that type of positions? By looking at the NYC jobs data set from 2013 to 2017,we wish to give some advice on job catrgory, required skills and salary for people who are seeking for a job.  

#Related work: 
Anything that inspired you, such as a paper, a web site, or something we discussed in class.
#Initial questions:
What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?
#Data: 
Source: https://data.cityofnewyork.us/City-Government/NYC-Jobs/kpav-sd4t/data
Scrape:We doWnloaded the data set from the website and the original data set contains 3174 job information. We selected data with information about work location, job category, preferred skills and full/part time. We want to use Google Map to get longtitute and latitute from work locations. Since the Google map has a limit of 2500 observation one time, we selected first 2500 observations from the data set.
Cleaning:
1. Merged job category if they are the same kind but just have different names. Finally we got 12 kinds of job categories.  
2. Unified salary unit to "Annual" and recalculated the salary range and average salary. 
3. Used Google Map to change location to longitute and latitute. 

#Exploratory analysis: 
Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.
#Additional analysis:
If you undertake formal statistical analyses, describe these in detail
#Discussion: 
What were your findings? Are they what you expect? What insights into the data can you make?

