---
title: "p8105"
author: "Qing Xu"
date: "November 21, 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(haven)
library(readxl)
library(janitor)
library(ggmap)
library(plotly)
library(stringr)
```
#clean data
```{r}
nyc_jobs<- read.csv("NYC_Jobs.csv") %>%
  clean_names() %>%
  filter(job_category!= " ", 
         full_time_part_time_indicator!=" ", 
         preferred_skills!= " ",
         work_location!=" ") %>%
  head(2500) #google map limited to 2500
nyc_jobs$job_category<- as.character(nyc_jobs$job_category)

#combine job category (function?)
for (i in 1:2500) {
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("engineering", ignore_case = TRUE))] <- "Engineering"
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("finance", ignore_case = TRUE))] <- "Finance"
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("legal", ignore_case = TRUE))] <- "Legal Affairs"
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("technology", ignore_case = TRUE))] <- "Technology"
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("policy", ignore_case = TRUE))] <- "Policy"
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("communi", ignore_case = TRUE))] <- "Community"
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("clerical", ignore_case = TRUE))] <- "Clerical"
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("social service", ignore_case = TRUE))] <- "Social service"
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("public safety", ignore_case = TRUE))] <- "Public safety"
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("administration", ignore_case = TRUE))] <- "Administration"
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("operations", ignore_case = TRUE))] <- "Maintance"
    nyc_jobs$job_category[[i]][str_detect(nyc_jobs$job_category[[i]],regex("maintenance ", ignore_case = TRUE))] <- "Maintance"
    
}


# change unit of salary and calculate mean
nyc_jobs$salary_frequency<-as.character((nyc_jobs$salary_frequency))
nyc_jobs$salary_range_from<- as.numeric(nyc_jobs$salary_range_from)
nyc_jobs$salary_range_to<- as.numeric(nyc_jobs$salary_range_to)

#function?
nyc_jobs$salary_range_from <- with(nyc_jobs, ifelse(salary_frequency == "Hourly", salary_range_from*1825,salary_range_from))
nyc_jobs$salary_range_to <- with(nyc_jobs, ifelse(salary_frequency == "Hourly", salary_range_to*1825,salary_range_to))
nyc_jobs$salary_range_from <- with(nyc_jobs, ifelse(salary_frequency == "Daily", salary_range_from*365*5/7,salary_range_from))
nyc_jobs$salary_range_to <- with(nyc_jobs, ifelse(salary_frequency == "Daily", salary_range_to*365*5/7,salary_range_to))

nyc_jobs<-mutate(nyc_jobs,salary_frequency="Annual") %>%
          mutate(salary_mean = (salary_range_to-salary_range_from)/2+salary_range_from)


# get lon and lat
nyc_jobs$work_location<-as.character(nyc_jobs$work_location)
geo <- geocode(location = nyc_jobs$work_location, output="latlon", source="google")
nyc_jobs<- nyc_jobs %>%
  mutate(lon = geo$lon, lat = geo$lat) %>%
  group_by(job_category)

```


```{r}
# plotly worldwild
Sys.setenv('MAPBOX_TOKEN' = 'pk.eyJ1IjoieHVxaW5nc2FsbHkiLCJhIjoiY2phZWh0djdyMHUzZTJ3bGR3MHFsdmIzZSJ9.vhYtu7zeAAuX6slhdDj6lA')

p <- nyc_jobs %>%
  mutate(text_label = str_c("Annual mean salary$:",salary_mean)) %>% 
  plot_mapbox(lat = ~lat, lon = ~lon,
              size=2,
              split = nyc_jobs$job_category,
              mode = 'scattermapbox') %>%
  add_markers(
    text = ~text_label,
    color = ~job_category,size = I(9)) %>%
  layout(title = 'Work Location',
         font = list(color='white'),
         plot_bgcolor = '#191A1A', paper_bgcolor = '#191A1A',
         mapbox = list(style = 'dark'),
         legend = list(orientation = 'h',
                       font = list(size = 8)),
         margin = list(l = 25, r = 25,
                       b = 25, t = 25,
                       pad = 2))
p
```

```{r} 
#alternative map
#For location in NYC(2500-611)
myLocation_nyc = c(-74.23,40.58,-73.75,40.87)
myMap_nyc <- get_map(location=myLocation_nyc,
                 source = "stamen",maptype = "watercolor", crop = FALSE) 
ggmap(myMap_nyc)+
    geom_point(aes(x = lon, y = lat), data = nyc_jobs,
      alpha = .5, color="darkred",size = 3) +
    labs(title = "Work location in NYC")

```

# Boxplot of salary in different job category
```{r}
nyc_jobs %>%
plot_ly(y = ~salary_mean, color = ~job_category, type = "box",
          colors = "Set2") %>%
layout(title = "Annual average salary distribution in 12 job categories")
```
# job type and educational requirement and salary
```{r}
job_data=nyc_jobs%>%
select(job_category, salary_range_from, salary_range_to,minimum_qual_requirements,full_time_part_time_indicator,salary_frequency)%>%
filter(job_category!= " ", minimum_qual_requirements!=" ",full_time_part_time_indicator=="F",salary_frequency=="Annual")%>%
  group_by(salary_range_from)%>%
  arrange(desc(salary_range_from))

master_data=filter(job_data,grepl("master's degree",minimum_qual_requirements),!grepl("baccalaureate",minimum_qual_requirements),!grepl("Baccalaureate",minimum_qual_requirements))
  

baccalaureate_data = filter(job_data,grepl(" baccalaureate ",minimum_qual_requirements),!grepl("Master's degree",minimum_qual_requirements), !grepl("master's degree",minimum_qual_requirements))

Other_data=filter(job_data,!grepl(" baccalaureate ",minimum_qual_requirements),!grepl("Master's degree",minimum_qual_requirements), !grepl("master's degree",minimum_qual_requirements), !grepl("Baccalaureate",minimum_qual_requirements))



master_plot=plot_ly(master_data, y = ~salary_range_from, color = ~job_category, type = "box", colors = "Set2")%>%
layout(title = "Base salary of different kind of jobs required only master degree")

baccalaureate_plot=plot_ly(baccalaureate_data, y = ~salary_range_from, color = ~job_category, type = "box", colors = "Set2")%>%
  layout(title = "Base salary of different kind of jobs required only baccalaureate degree")
  
Other_plot=plot_ly(Other_data, y = ~salary_range_from, color = ~job_category, type = "box",
          colors = "Set2")%>%
  layout(title = "Base salary of different kind of jobs without requirement of degree")



```